### ISSUE TITLE
Rename Buildpack?

### ISSUE THREAD

**Issue by joefitzgerald** [cloudfoundry-community/dotnet-core-buildpack#43]
Because ASP.NET 5 !== what this is anymore...

Potential name options:

* dotnet-buildpack  ~~(:+1: for my vote)~~
* dotnet-core-buildpack  (:+1: for my vote)
* aspnet-core-buildpack
* aspnet-buildpack

**Comment by autodidaddict** [comment]
As this buildpack only applies to ASP.NET Core applications and not generically .NET core (it's not like this is designed for console apps), I suggest **aspnet-core-buildpack**.  By not supplying **core** you run the risk of someone thinking this might apply to legacy .NET, or some kind of legacy mono app.

**Comment by joefitzgerald** [comment]
Why couldn't this also run console apps?

**Comment by joefitzgerald** [comment]
> By not supplying core you run the risk of someone thinking this might apply to legacy .NET, or some kind of legacy mono app.

Using that line of reasoning we should have a java-8-buildpack to avoid confusion that it does not run 1.4 apps.

**Comment by autodidaddict** [comment]
Because console apps don't listen on an HTTP port, and console apps in the traditional sense (e.g. without ASP.NET self-starting Kestrel) will fail a CF health check.

**Comment by joefitzgerald** [comment]
Apps can be started with --no-route and work against a message broker (e.g. RabbitMQ).

**Comment by autodidaddict** [comment]
> Using that line of reasoning we should have a java-8-buildpack to avoid confusion that it does not run 1.4 apps.

The difference between Core and 4.6 is not the same as the difference between Java 7 and 8.

**Comment by autodidaddict** [comment]
I vote for **dotnet-core-buildpack**

**Comment by joefitzgerald** [comment]
> I vote for dotnet-core-buildpack

OK, 👍  on that.

**Comment by sacooper-pivotal** [comment]
I vote for dotnet-core-buildpack

**Comment by degrim** [comment]
Technically the buildpack does pass a parameter to kestrel through the command-line right now giving it a server-urls parameter, this is something specific to a web app.  Even with that parameter being passed, console apps could still run but they would receive those parameters from the command-line.

**Comment by joefitzgerald** [comment]
@degrim noted. I suppose the question isn't so much the current state, but what the buildpack aspires to be? I think it should allow apps to start with or without a (HTTP/S) route, particularly given future TCP routing capabilities.

**Comment by degrim** [comment]
@joefitzgerald I think before the changes in RC2 to use the .Net CLI, it didn't make sense for this buildpack to also try to support console apps.  But now that ASP.Net runs on top of the same CLI as .Net console apps, it makes a little more sense to accommodate this scenario as well.

**Comment by degrim** [comment]
> Using that line of reasoning we should have a java-8-buildpack to avoid confusion that it does not run 1.4 apps.
That's not entirely true, this buildpack supports ASP.Net Core (and now .Net Core console apps?) which is a different product than ASP.Net and Classic ASP.  ASP.Net 1.0 released in 2002, ASP.Net Core 1.0 releases later this year.

**Comment by joefitzgerald** [comment]
@degrim yes, @autodidaddict hashed it out via Slack and I agree - `core` should be part of the name.

**Comment by degrim** [comment]
Console apps do indeed work with --no-route, so my vote would be for dotnet-core-buildpack.

**Comment by opiethehokie** [comment]
buildpack renamed

**Comment by joefitzgerald** [comment]
🎉
