### ISSUE TITLE
InsufficientResources after cf push

### ISSUE THREAD

**Issue by ritazh** [cloudfoundry-community/dotnet-core-buildpack#49]
Getting `InsufficientResources` error after pushing both the Hello World sample and my own asp.net RC2 sample app as described in the README.

Deployment commands for your reference:
```
cf push aspnetcoreapp -m 1g -b https://github.com/cloudfoundry-community/asp.net5-buildpack.git --no-start
cf enable-diego aspnetcoreapp
cf start aspnetcoreapp
```

My code: https://github.com/ritazh/aspnetcoreapp-cf

Environment information:
```
+--------------+-----------+-------------+
| Name         | Versions  | Commit Hash |
+--------------+-----------+-------------+
| cf           | 231*      | f67ebb73+   |
| diego        | 0.1455.0* | 6a3aebf4    |
| etcd         | 36*       | 993cbd05    |
| garden-linux | 0.334.0*  | 88f7ec39    |
+--------------+-----------+-------------+
```

**Comment by seanobrienatvirtustreamcom** [comment]
I can't get bluemix to compile the application. I get an error

The type or namespace name 'ConfigurationBuilder' could not be found ...

I have attached my logs

[aspnetcorecf2016_logdump.txt](https://github.com/cloudfoundry-community/asp.net5-buildpack/files/279980/aspnetcorecf2016_logdump.txt)

**Comment by ritazh** [comment]
Thanks @seanobrienatvirtustreamcom Just updated the code in my [repo](https://github.com/ritazh/aspnetcoreapp-cf) to remove ConfigurationBuilder. Still getting the same error.

**Comment by seanobrienatvirtustreamcom** [comment]
Builds fine, I can start it fine, but CF gives errors on the health check 

'"failed to accept connections within health check timeout"

I believe you are scheduled to speak at CF Summit (where I'm sitting right now :p) Hope this doesn't impact your presentation!

[aspnetcorecf2016_pushattempt2.txt](https://github.com/cloudfoundry-community/asp.net5-buildpack/files/280067/aspnetcorecf2016_pushattempt2.txt)


[logsaftersuccessfulbuild.txt](https://github.com/cloudfoundry-community/asp.net5-buildpack/files/280065/logsaftersuccessfulbuild.txt)

**Comment by degrim** [comment]
Removing the ConfigurationBuilder will cause it to fail, because the app is not being told to listen on the right port anymore.  The buildpack passes command-line arguments to Kestrel (--server.urls http://0.0.0.0:$PORT).  If you want to run without using ConfigurationBuilder you'll need to use `.UseUrls()` to specify the right host/port to listen on.

**Comment by ritazh** [comment]
@seanobrienatvirtustreamcom yes...this is blocking it. would be great to fix this before tomorrow. @degrim I originally added `ConfigurationBuilder` per your documentation but that failed. So I removed it. I can give `.UseUrls()` a try.

**Comment by degrim** [comment]
You also need to add `using Microsoft.Extensions.Configuration;` to the file which uses ConfigurationBuilder.  I'll add that to the Readme as it seems to be missing.

**Comment by ritazh** [comment]
Thanks @degrim Should I still try using `ConfigurationBuilder`? Note, this is an asp.net RC2 app.

**Comment by degrim** [comment]
Yes, I would use ConfigurationBuilder.  If you just add the using statement to what you already had, it should compile then.

**Comment by ritazh** [comment]
argh...still the same error. You can see my latest commit in my repo.

**Comment by degrim** [comment]
Is the app running out of disk space?  How much is allocated to this app?  You can try publishing the app as a self-contained app and pushing that way, it should only require ~20MB when published with the runtime.

**Comment by opiethehokie** [comment]
@ritazh are you sure the InsufficientResources error is specific to this buildpack? It almost seems like your diego doesn't have enough memory/disk to start another app.

**Comment by seanobrienatvirtustreamcom** [comment]
@ritazh I got your app working in bluemix. Let me know if you need help. I can swing by Microsoft booth.

http://aspnetcorecf2016.mybluemix.net/

**Comment by ritazh** [comment]
@seanobrienatvirtustreamcom ah nice!!! I'm not at the summit until tomorrow. I'm adding more resources to the diego components in my cf cluster now. Waiting for all the nodes to come back up.

**Comment by ritazh** [comment]
Hey guys, after I resized the diego nodes, pushed the app again, got this error: "NoCompatibleCell". Then searched online and saw that I should not do `cf enable-diego aspnetcoreapp`. So I'm getting good output like below, but the deployment gets stuck at the end and ends with `failed to stage within 15.000000 minutes`. Let me know if you are around today. Maybe we can meet in the exhibit hall.

```
-----> Downloaded app package (56K)
Cloning into '/tmp/buildpacks/asp.net5-buildpack'...
Submodule 'compile-extensions' (https://github.com/cloudfoundry-incubator/compile-extensions.git) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '4a0e48afc46c1d467b7c75a8ae5e6f3a044d3d64'
ASP.NET Core buildpack version: 0.8.0
ASP.NET Core buildpack starting compile
-----> Restoring files from buildpack cache
....
log  : Restore completed in 74626ms.
```

**Comment by opiethehokie** [comment]
Feel free to reopen this if you still think there is still a problem, but I'm closing for now as it seems to be related to the app/CF and not the buildpack.
