### ISSUE TITLE
usage documentation incorrect?

### ISSUE THREAD

**Issue by nam-pt-do** [cloudfoundry-community/dotnet-core-buildpack#54]
Not a but, but the documentation in the top page is refering to the old asp.net5 project.

Usage:

   cf push my_app -b https://github.com/cloudfoundry-community/asp.net5-buildpack.git

Should it not be pointing to the current core project.

   cf push my_app -b https://github.com/cloudfoundry-community/dotnet-core-buildpack.git

**Comment by degrim** [comment]
It should, but github should also redirect the request automatically since the buildpack was just renamed.

**Comment by degrim** [comment]
PR #53 fixes this.
