### ISSUE TITLE
Add support for running pre/post build scripts during staging

### ISSUE THREAD

**Issue by degrim** [cloudfoundry-community/dotnet-core-buildpack#60]
Right now, there is no NPM, Bower, or Gulp installation in the droplet to run the `prebuild`or `postbuild` scripts defined in an application's `project.json` file during staging.  
In order to fully support a scenario where a user can push their application's code and have these scripts be run during staging, we would need to add at least NodeJS and NPM to the buildpack as cached dependencies.  
Potential drawbacks of this approach are:

- Increased droplet size due to the inclusion of NodeJS and NPM.
- Increased staging time due to running pre/post build scripts during staging

Current workarounds are:

- Run all pre/post build scripts before pushing the application (cannot be done if using a DevOps pipeline to push automatically from a Git repository where npm/bower packages are not checked in unless part of that pipeline executes these scripts instead)

I'm thinking that if we do include NodeJS and NPM to support these use cases, we would only install them when there was a `prebuild` or `postbuild` script defined in the `project.json` file so that users who do not use these scripts are unaffected by the extra binaries being included.  
Does anyone else have any thoughts on this?

**Comment by Dannyzen** [comment]
@degrim would heroku's [Mutlibuildpack](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) approach work here?

**Comment by degrim** [comment]
@Dannyzen That wouldn't really fit this use case because you wouldn't be pushing a NodeJS app, you would just be using NodeJS to install NPM and bower to restore client-side js packages to your ASP.NET app, after the packages are restored the Node/NPM installation could be removed even.

**Comment by degrim** [comment]
@dgodd, @RochesterinNYC, @geramirez
Any thoughts on this?

**Comment by RochesterinNYC** [comment]
@degrim I think that including a node runtime in the buildpack is an acceptable way to go. We do something similar for the Ruby buildpack (including a node runtime in a non-node buildpack): https://github.com/cloudfoundry/ruby-buildpack/blob/master/manifest.yml#L31-L36 & https://github.com/cloudfoundry/ruby-buildpack/blob/master/lib/language_pack/helpers/node_installer.rb

I'd advise that if this was to be done, though, only offering one controlled version of node or something. Trying to be flexible/allowing many versions leads to the introduction of the hairiness of the node ecosystem into this buildpack, where node isn't really the concern/focus.

**Comment by RochesterinNYC** [comment]
Additionally, I think only installing node if it's required (if the `prebuild` or `postscript` scripts are defined) is a great approach to take.

**Comment by degrim** [comment]
@RochesterinNYC I agree we should only offer one node version, would probably be best to install the same version that gets installed with Visual Studio.
