### ISSUE TITLE
Update To .NET Core 1.0

### ISSUE THREAD

**Issue by joefitzgerald** [cloudfoundry-community/dotnet-core-buildpack#61]
https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/

**Comment by emailtowalter** [comment]
Folks here did a fantastic job to update the buildpack to support RC2 literally 1 day after RC2 release. Trust the team will do the similar thing.  Thanks.

**Comment by degrim** [comment]
It seems Microsoft didn't add the new tooling build to the same stream that we were getting the previous build from, so we'll have to change how we pull in that dependency.  Merging #56 would be a good first step to adding support for the preview2 build.

**Comment by degrim** [comment]
#64 resolves this.

**Comment by degrim** [comment]
Closing this issue as the buildpack now supports both .NET Core 1.0 RC2 and RTM.
