### ISSUE TITLE
pushing RC2 app failed

### ISSUE THREAD

**Issue by emailtowalter** [cloudfoundry-community/dotnet-core-buildpack#66]
Hi... not sure if the build pack is in the middle of the upgrade. When cf push the RC2 app to  pivotal CF and bluemix few min ago, both failed. both went to the last step, but failed at start the instance step. 

Error from bluemix:
2016-06-28T21:18:51.48-0400 [API/4]      OUT App instance exited with guid 99774
5c6-e5c3-43dc-b2c6-6b8fb42462eb payload: {"cc_partition"=>"default", "droplet"=>
"997745c6-e5c3-43dc-b2c6-6b8fb42462eb", "version"=>"817c2582-f730-4e42-b374-8e30
6f9a86ce", "instance"=>"49e38e2918b1425baccf92933a8c1721", "index"=>0, "reason"=
>"CRASHED", "exit_status"=>-1, "exit_description"=>"failed to start", "crash_tim
estamp"=>1467163131}

command line: cf push myappname -b https://github.com/cloudfoundry-community/dotnet-core-buildpack.git

The source code is uploaded here if you need to take a look : https://github.com/emailtowalter/webapplication7

**Comment by degrim** [comment]
@emailtowalter I was able to push the app to Bluemix without any crash.

**Comment by emailtowalter** [comment]
Hi... did you try to use the app I attached here? I tried now, and still failed. Here is the CF push result. By the way, I did not install any RTM version of .net core yet. 

C:\Walter\MyCode\Code\ASPNET\WebApplication6\src\WebApplication6>cf push ninja1
-b https://github.com/cloudfoundry-community/dotnet-core-buildpack.git
Updating app ninja1 in org ninjawu / space dev as emailtowalter@yahoo.com...
OK

Uploading ninja1...
Uploading app files from: C:\Walter\MyCode\Code\ASPNET\WebApplication6\src\WebAp
plication6
Uploading 5.4M, 2059 files
Done uploading
OK

Starting app ninja1 in org ninjawu / space dev as emailtowalter@yahoo.com...
-----> Downloaded app package (2.9M)
-----> Downloaded app buildpack cache (310M)
    Cloning into '/tmp/buildpacks/dotnet-core-buildpack'...
    Submodule 'compile-extensions' (https://github.com/cloudfoundry-incubator/co
mpile-extensions.git) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '4a0e48afc46c1d467b7c75a8ae5e6f
3a044d3d64'
ASP.NET Core buildpack version: 0.8.0
ASP.NET Core buildpack starting compile
-----> Restoring files from buildpack cache
       Copied 207 files from /tmp/cache/.dotnet to /tmp/staged/app
       Copied 18570 files from /tmp/cache/.nuget to /tmp/staged/app
       OK
-----> Extracting libunwind
       OK
-----> Installing Dotnet CLI
       OK
-----> Restoring dependencies with Dotnet CLI
       log  : Restoring packages for /tmp/staged/app/project.json...
       log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in
/tmp/staged/app/project.json...
       log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegr
ation.Tools' in /tmp/staged/app/project.json...
       log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools'
in /tmp/staged/app/project.json...
       log  : Restoring packages for tool 'Microsoft.Extensions.SecretManager.To
ols' in /tmp/staged/app/project.json...
       log  : Restoring packages for tool 'Microsoft.VisualStudio.Web.CodeGenera
tion.Tools' in /tmp/staged/app/project.json...
       log  : Writing lock file to disk. Path: /tmp/staged/app/project.lock.json

       log  : ./project.json
       log  : Restore completed in 5536ms.
       OK
-----> Saving to buildpack cache
       Copied 0 files from /tmp/staged/app/.dotnet to /tmp/cache
       Copied 0 files from /tmp/staged/app/.nuget to /tmp/cache
       OK
ASP.NET Core buildpack is done creating the droplet
-----> Uploading droplet (312M)

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down

**Comment by degrim** [comment]
I cloned the git repo that you posted and pushed it.  Your cache seems to have quite a few more packages than a fresh install, if you were previously using this same app with pre-release packages that are not compatible with the RC2 packages that might cause it to crash because those packages are still in the cache and some of your dependencies may contain a dependency with a wildcard that ends up pulling in the newer pre-release package.  Your cache has over 5000 more packages than what I get from the `dotnet restore` command.  Try deleting the app and repushing so that the old cache is cleared.

**Comment by emailtowalter** [comment]
I deleted all apps in bluemix, and repush, I do see more on the commandline. But it still failed. I updated the CF-push log https://github.com/emailtowalter/webapplication7/blob/master/cfpushlog.txt

Not sure what is going on.

Thanks,

**Comment by degrim** [comment]
Are you pushing the app from the solution folder or the project folder?  If you're not pushing from the solution folder the buildpack will default to the preview2 tools (as shown in your log) rather than the value in your [global.json file](https://github.com/emailtowalter/webapplication7/blob/master/global.json#L4).  Note that you'll need to delete and recreate the app to switch back to the preview1 tools after the preview2 tools have been installed as well.

**Comment by emailtowalter** [comment]
You are right. I pushed from project folder. Now when I push from solution folder, the site structure is weird and MVC does not work. I assume you did something different? 

My folder structure: 
solution folder\
     -- global.json
      -- \src\
            -- WebApplication6
                   --wwwroot
                   -- project.json

**Comment by degrim** [comment]
You'll need to update your project.json and Program.cs files so that the app can be run with the command `dotnet run -p src/WebApplication6` from the solution folder.  See emailtowalter/webapplication7#1 for details on the changes.

**Comment by emailtowalter** [comment]
well, it worked for CF, but it broke the local debug when I run locally using kestrel. here is the error. I am about to move to RMT and preview 2.  I do not know if this problem will stay. 

"{"Unable to locate a project.json at 'C:\\Walter\\MyCode\\Code\\ASPNET\\WebApplication6\\src\\WebApplication6\\bin\\Debug\\netcoreapp1.0\\'."}"

**Comment by degrim** [comment]
Add "project.json" to the list of files under the copyToOutput->include section of project.json.  Then rebuild the solution (restarting it will not always trigger this copy script to run if the source files have not changed).

**Comment by emailtowalter** [comment]
great. Worked. Before I close it, just want to know if I need to do the same once I upgrade to RTM version of .net core and preview 2 of tooling? 

I also want you to know that you have saved me ton's hours that I would lose otherwise. Thanks!

**Comment by degrim** [comment]
For now, when you change .NET CLI versions you'll have to delete and repush your app.  This will probably change in the future, just need to determine the best way to detect which version is already in the cache and use that information to decide whether or not to install a new version.

**Comment by emailtowalter** [comment]
ops, recf push , it gave me a error. I think it is due to the project.json change. I could rollback the change for CF and add it back in for local debug, but just toooooo much trouble.

 : "ASP.NET Core buildpack is done creating the droplet
/tmp/buildpacks/dotnet-core-buildpack/lib/buildpack/app_dir.rb:65:in `main_proje
ct_path': Multiple paths contain a project.json file, but no .deployment file wa
s used (RuntimeError)
        from /tmp/buildpacks/dotnet-core-buildpack/lib/buildpack/release/release
r.rb:61:in `get_start_cmd'
        from /tmp/buildpacks/dotnet-core-buildpack/lib/buildpack/release/release
r.rb:23:in `release'
        from /tmp/buildpacks/dotnet-core-buildpack/lib/buildpack.rb:45:in `relea
se'
        from /tmp/buildpacks/dotnet-core-buildpack/bin/release:26:in `<main>'
Staging failed: Release info failed:"

**Comment by degrim** [comment]
Regarding the project.json issue, you can create a file called `.cfignore` in the folder you're running the cf command from and put the line `bin/` in there to exclude the bin folder from the `cf push`.

**Comment by emailtowalter** [comment]
I ended up to migrate to RTM and preview 2. Everything worked charmly without going through all the troubles mentioned here. 

Thumb up to the team here for the super fast upgrade and quick response.
