### ISSUE TITLE
how to CF push website along with multiple class libs

### ISSUE THREAD

**Issue by emailtowalter** [cloudfoundry-community/dotnet-core-buildpack#74]
Hi... I have a main website and multiple class library projects which is referenced by the website project. All these projects are under the the same solution folder. 

What is the way to CF push the site and along with the dependency projects ? 

Thanks, 

Walter

**Comment by degrim** [comment]
You can create a `.deployment` file which specifies the web project and then push the application from the solution folder.  That should result in all of the libraries and the web project being pushed and compiled, but only the web project will be passed to the `dotnet run` command.

**Comment by emailtowalter** [comment]
I tried. Yes, it passed the CF push, but site URL does not work anymore. For example: if I type http://ninjalocal.bm.devfg.rbc.com/. I do not see view anymore. 

Not sure if I miss anything. Attach the zip. 

Please help. Thanks

[MultiProjects.zip](https://github.com/cloudfoundry-community/dotnet-core-buildpack/files/382846/MultiProjects.zip)

**Comment by degrim** [comment]
Remove the line ".UseContentRoot(Directory.GetCurrentDirectory())" from your Program.cs.  This is making dotnet look for Views in the solution folder, rather than inside the bin folder.

Once that is removed you'll need to add some settings to your project.json to make the Views folder copy to your output bin folder.

Change your "buildOptions" section in project.json from this:
```
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
```

to this:
```
  "buildOptions": {
    "copyToOutput": {
      "include": [
        "**.cshtml",
        "wwwroot"
      ],
      "exclude": [ "bin", "obj" ]
    },
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
```

This will copy the "wwwroot" folder and all views into the bin folder, maintaining the directory structure you have for your areas.

**Comment by emailtowalter** [comment]
workded. I guess all execution dependency items need to be moved into bin folder, e.g. appsetting.json. With the change, env.WebRootPath in startup.cs is empty. Not sure what the impact is. Leave to future to find out. Just want you to know. 

Maybe a separate note: now all source codes are on bluemix, then compiled. Waste of space. Is there a approach to just push the published items there using this buildpack? I would assume I have to have a ubuntu machine to build locally, then run CF there?

Thanks,

**Comment by degrim** [comment]
Yes, you will need to copy any json configuration files that you depend on to the output folder as well.  You can publish the Ubuntu binaries from a Windows/Mac machine using the `dotnet publish` command.  You just need to add the runtimes that you want to target to your project.json file.

Example project.json runtimes section:
```
"runtimes": {
    "win10-x64": {},
    "win7-x64": {},
    "osx.10.11-x64": {},
    "ubuntu.14.04-x64": {}
}
```

Adding this section to your project.json will allow you to run `dotnet publish -o outputFolder -r ubuntu.14.04-x64 src/MyWeb` to publish the Ubuntu binaries from your Windows/Mac machine which are compatible with running on Bluemix using this buildpack.  The "-o" option will put the files in "outputFolder" which you can change to any convenient location for your published files to be placed.
