### ISSUE TITLE
Specs broken on Ruby 2.3.1

### ISSUE THREAD

**Issue by RochesterinNYC** [cloudfoundry-community/dotnet-core-buildpack#78]
The recent PR relating to NPM (#76) seems to have broken the test suite on `ruby 2.3.1`. The unit tests are failing due to singleton TypeErrors.

The errors are visible here:
https://buildpacks.ci.cf-app.com/pipelines/dotnet-core-buildpack/jobs/specs-lts-master/builds/6
https://buildpacks.ci.cf-app.com/pipelines/dotnet-core-buildpack/jobs/specs-edge-master/builds/4

For context, we have a CI pipeline that tracks new commits to master for this buildpack and runs the unit and integration tests against the commits. We noticed this breakage because our CI docker image is based off a `ruby 2.3.1` image.

-- @sesmith177

**Comment by opiethehokie** [comment]
Is a move to `ruby 2.3.1` imminent? I haven't seen anything about it. I do realize it's the latest stable though, not saying this shouldn't be fixed.

**Comment by RochesterinNYC** [comment]
Is what moving to `ruby 2.3.1` imminent? We recently bumped all of our buildpacks to `ruby 2.3.1` (for the test suites and buildpack packager and etc.), so this issue came up.

`ruby 2.3.x` series could be added to the travis test matrix perhaps?

**Comment by degrim** [comment]
I think he was referring to the fact that the cflinuxfs2 stack doesn't include ruby 2.3.1 right now.

**Comment by RochesterinNYC** [comment]
Ah gotcha. Nope, I don't think there's any current ongoing discussions about changing the ruby default to 2.3.1 in cflinuxfs2.
