### ISSUE TITLE
issue while deploying the .NET core build pack in PCF

### ISSUE THREAD

**Issue by VenkateshSrinivasan** [cloudfoundry-community/dotnet-core-buildpack#80]
Hi,
After deploying this a .NET core app with this build pack in pivotal web service, The health check was failing. on observation it was found that the this build pack is trying to start the application with server.url = 0.0.0:**${port}** . When I contacted the support, the support engineer told us that pivotal web service would not be able to start application without the {} braces. Could you please correct the same or tell us an work around for the same

**Comment by degrim** [comment]
A workaround would be to add `.UseUrls('http://*:' + Environment.GetEnvironmentVariable('PORT'))` instead of the `.UseConfiguration(config)` line suggested in the readme.

**Comment by autodidaddict** [comment]
Actually if you add `.UseCommandLine()` .NET core automatically recognizes the server.urls parameter passed as part of the start command provided by the buildpack. You don't need to use `.UseUrls` explicitly.

**Comment by degrim** [comment]
@VenkateshSrinivasan , 
  Looking at the command we're using to start the application, we are passing `--server.urls http://0.0.0.0:${PORT}` as required.  Are you using the `.AddCommandLine()` option as @autodidaddict said?

**Comment by VenkateshSrinivasan** [comment]
No. I did not use .AddCommandLine. I had a discussion with Pivotal web service team and as per them it should not  b e ${PORT}. It should be http://0.0.0:$PORT **without flower braces ({})**

**Comment by autodidaddict** [comment]
@VenkateshSrinivasan using the buildpack, you can just add `.AddCommandLine()` to your application's startup config, and the buildpack will _set the start command for you_ to exactly what is appropriate. This has been proven to work for quite some time now, I just pushed an app 30 seconds ago to both PWS and a private foundation using the buildpack in this fashion.

**Comment by VenkateshSrinivasan** [comment]
@degrim and @autodidaddict ,
Do we need to do any other settings as stated in this blog http://harrewijnen.net/my-first-asp-net-core-app-on-cloud-foundry/

**Comment by autodidaddict** [comment]
@VenkateshSrinivasan you do _not_ need to specify the start command in your manifest, as that is supplied for you by the buildpack.

**Comment by degrim** [comment]
@VenkateshSrinivasan ,
  That blog post was referring to pushing an app for ASP.NET Core 1.0 RC1, many things changed in ASP.NET Core with RC2 and RTM versions.  See [the buildpack readme](https://github.com/cloudfoundry-community/dotnet-core-buildpack#using-samples-from-the-cli-samples-repository) for info on what changes need to be made to the default Visual Studio or Yeoman templates to make your application work with this buildpack.

**Comment by VenkateshSrini** [comment]
@degrim and @autodidaddict,
My application worked with these changes.Thanks to all
