### ISSUE TITLE
Unable to access LocalDB in PWS

### ISSUE THREAD

**Issue by VenkateshSrini** [cloudfoundry-community/dotnet-core-buildpack#81]
Hi,

My connection string looks something like this 
{
  "ConnectionStrings": {
    "DefaultConnection": "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=%CONTENTROOTPATH%/App_Data/ASPNETCoreToDo.mdf;"
  }
}
During the publish process I have include the App_data folder also and I hope with cf push the same would have got published in PWS also (since id not use CFIGNORE flag). 

The =%CONTENTROOTPATH% is also perfectly replaced with Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=/home/vcap/app/App_Data/ASPNETCoreToDo.mdf

But in spite of all these things I see that in PWS I get this error
**System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address**

Any suggestion what could be the issue.

Thanks and regards
Venkatesh

**Comment by opiethehokie** [comment]
This buildpack doesn't have any database-specific behavior so I don't think this is the proper forum for the question. I'd suggest asking on stackoverflow.
