### ISSUE TITLE
cf push error

### ISSUE THREAD

**Issue by akbmjain** [cloudfoundry-community/dotnet-core-buildpack#83]
Hi,

When I try to push .NET MVC Core in cloud foundry I get error

cf push webcore -b https://github.com/cloudfoundry-community/dotnet-core-buildpack.git

Error:

ERR The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc2-3002702' was not found.
2016-08-11T12:11:21.21+0000 [APP/0]      ERR   - Check application dependencies and target a framework version installed at:
2016-08-11T12:11:21.21+0000 [APP/0]      ERR       /home/vcap/app/.dotnet/shared/Microsoft.NETCore.App
2016-08-11T12:11:21.21+0000 [APP/0]      ERR   - The following versions are installed:
2016-08-11T12:11:21.21+0000 [APP/0]      ERR       1.0.0
2016-08-11T12:11:21.21+0000 [APP/0]      ERR   - Alternatively, install the framework version '1.0.0-rc2-3002702'.
2016-08-11T12:11:21.22+0000 [APP/0]      OUT Exit status 131

My project.json file:

{
  "userSecretsId": "aspnet-WebCoreApp-92f6f94d-a36f-4039-8769-5c9c28f02771",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc":  {
      "version": "1.0.0-preview1-final",
      "type": "build"
    }
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },
    "Microsoft.Extensions.SecretManager.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

Any clue what's wrong?

Thanks

**Comment by degrim** [comment]
The buildpack is installing .NET Core 1.0 RTM, your application was published as a portable application targetting .NET Core 1.0 RC2.  You can either update the application for .NET Core 1.0 RTM, or make it a self-contained application which contains the RC2 runtime to work around this.  I would recommend upgrading to the RTM runtime, this shouldn't require much changes to your application code as the changes from RC2 to RTM were very minimal.
  At some point in the near future we should probably add support for running non-latest runtime in a portable application.

**Comment by akbmjain** [comment]
**@degrim** Thanks for your response. I migrated my .NET Core 1.0 R2 app to .NET Core 1.0.
When I tried to push the app its giving time out error. Its trying around 20 times to get it started and its failing with time out error. I also added $PORT env variable in manifest.yml file but still no luck.

Any clues?

**Comment by degrim** [comment]
The PORT environment variable is provided by CF, you shouldn't be overriding it in manifest.yml.  You need to make your application listen on whatever port is specified in that variable.  See [this section](https://github.com/cloudfoundry-community/dotnet-core-buildpack#using-samples-from-the-cli-samples-repository) of the buildpack readme to configure this in your application.

**Comment by aniljain100** [comment]
**@degrim** Thanks for your help!! It worked with .NET Core 1.0.
One question: Is there a build which supports .NET Core 1.0 R2 also. If yes, can you give me the build pack URL?

We can close this issue.

Thanks

**Comment by degrim** [comment]
@aniljain100 #86 should add support for RC2 portable applications when it's merged, but we are likely to remove RC2 support when the support for 1.0.1 is added after it gets released this month.

**Comment by aniljain100** [comment]
**@degrim**  Thanks for helping me push the .NET Core app on cloud.

Cheers!!
