### ISSUE TITLE
Github release tag does not match the release name

### ISSUE THREAD

**Issue by RochesterinNYC** [cloudfoundry-community/dotnet-core-buildpack#92]
For github release [1.0.0 of the Dotnet Core Buildpack](https://github.com/cloudfoundry-community/dotnet-core-buildpack/releases/tag/v1.0), the associated tag does not match the name of the release. The tag is `v1.0` but the release is named `v1.0.0`.

This makes it a bit difficult to write automation around the buildpack releases here. For example, it's not super straightforward to generate the link to the release notes for a buildpack based off the release version (i.e. https://github.com/cloudfoundry-community/dotnet-core-buildpack/releases/tag/v1.0.0 does not exist).

**Comment by opiethehokie** [comment]
Sorry about that. I created a v1.0.0 tag and associated the release with it.

**Comment by RochesterinNYC** [comment]
Great, thanks!
